"""initial schema

Revision ID: fef46262cb96
Revises: 
Create Date: 2026-03-31 09:52:19.929850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fef46262cb96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('opened_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['opened_at'], ['transmissions.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thread_events',
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('thread_id', 'event_id')
    )
    op.create_table('transmissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('talkgroup_id', sa.Integer(), nullable=False),
    sa.Column('source_unit', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('encryption_status', sa.Boolean(), nullable=False),
    sa.Column('audio_path', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('asr_model', sa.String(), nullable=True),
    sa.Column('asr_confidence', sa.Float(), nullable=True),
    sa.Column('asr_passes', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('thread_decision', sa.String(), nullable=True),
    sa.Column('event_decision', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routing_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('packet_id', sa.String(), nullable=False),
    sa.Column('thread_decision', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('event_decision', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['packet_id'], ['transmissions.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routing_records')
    op.drop_table('transmissions')
    op.drop_table('thread_events')
    op.drop_table('threads')
    op.drop_table('events')
    # ### end Alembic commands ###
